### ISSUE TITLE
material design .import.less is not imported for main.less

### ISSUE THREAD

**Issue by yubozhao** [npvn/meteor-material-design#2]

**Comment by npvn** [comment]
Do you mean the file `material.import.less`? In fact it is imported in `material-wfont.import.less`, which is then imported by `main.less`.

**Comment by yubozhao** [comment]
doesn't it make sense to import font into material.import.less and main.less import material.import.less?

**Comment by npvn** [comment]
I guess FezVrasta did this so people can have a choice: They can have the font downloaded from Google by using `material-wfont.import.less`, or they can use `material.import.less` instead and import the font themselves.

**Comment by yubozhao** [comment]
Ok, that make sense to me.  Thanks for clearing that.
